### PR TITLE
Consolidate packages into @vivid-planet/react-admin

### PR DESCRIPTION
**Pull request by fraxachun**

### CODE REVIEW

**Comment by dkarnutsch** [comment]
Why do react-admin-rte ("@vivid-planet/react-admin": "^1.0.0-alpha.18"), react-admin-color-picker (^1.0.0-alpha.47) and react-admin-date-picker (^1.0.0-alpha.1) all require different versions of the newly created react-admin package?

**Comment by fraxachun** [comment]
@dkarnutsch You're right. I updated to the new versioning schema (0.1.0)

**Review by dkarnutsch — APPROVED** [review]

**Comment by rabengraph** [comment]
my review is mistakenly here https://github.com/vivid-planet/react-admin/pull/235

**Comment by fraxachun** [comment]
> my review is mistakenly here #235

See https://github.com/vivid-planet/react-admin/issues/241

**Review by rabengraph — APPROVED** [review]

**Comment by fraxachun** [comment]
@nsams Can I merge this? I want to make https://github.com/vivid-planet/react-admin/issues/241 into a separate PR.

**Pull request merged**
