### PR TITLE
Implement a "Higher Order Hook" (HoH) for useTableQuery that avoids manual creation of <TableQuery

### PR DESCRIPTION
**Pull request by nsams**
this is highly inspired by https://github.com/apollographql/react-apollo/pull/3079

TODO: naming!!

### CODE REVIEW

**Comment by fraxachun** [comment]
Naming suggestion: performTableQuery
I think use... is not necessary as it behaves quite differently to common hooks

**Comment by nsams** [comment]
hooks müssen mit `use` beginnen

**Comment by fraxachun** [comment]
Maybe "useTableQueryData" as it returns tableData?

**Comment by nsams** [comment]
probably add a render prefix, as the hook does the rendering itself `useRenderTableQuery`

**Comment by nsams** [comment]
Or, make this behavior the default for useTableQuery

**Comment by fraxachun** [comment]
Another suggestion: useRenderTableQuery(query, config, renderFunction)
Use a render function instead of a HoC
Naming with render sounds good
I dislike this as default behaviour because it just behaves differently to the hooks we're used to.

**Pull request closed without merging**
